### ISSUE TITLE
Citrix missing fields

### ISSUE THREAD

**Issue by andrewstucki** [adriansr/nwdevice2filebeat#6]
Missing ECS fields:

- event.original
- observer.type
- observer.vendor
- related.ip
- tags

Missing other fields (injected by agent):

- agent.hostname
- elastic_agent.id
- elastic_agent.snapshot
- elastic_agent.version
- input.type
- log.flags
- log.source.address

**Comment by adriansr** [comment]
This was fixed in a72d8035658e3c05f6d6073c0543b5b195cb125b
